name: Forms
version: "1.2.6"
license: "GPL-2.0-or-later"
date: 2021-07-29
description: |
    Sesquilinear and Quadratic

authors:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Jan De Beule
      url: http://www.debeule.eu

maintainers:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Jan De Beule
      url: http://www.debeule.eu

GAP: ">=4.9"

www: https://gap-packages.github.io/Forms
readme: README
packageinfo: https://gap-packages.github.io/Forms/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Forms/releases/download/v1.2.6/Forms-1.2.6.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/Forms/releases/download/v1.2.6/Forms-1.2.6.zip
    - name: .tar.bz2
      url: https://github.com/gap-packages/Forms/releases/download/v1.2.6/Forms-1.2.6.tar.bz2

abstract: |
    This package can be used for work with sesquilinear and quadratic forms on finite vector spaces; objects that are used to describe polar spaces and classical groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Forms, Sesquilinear, Quadratic.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BB21</span>]   <b class='BibAuthor'>Bamberg, J. and De Beule, J.</b>,
     <i class='BibTitle'>Forms, Sesquilinear and Quadratic,
             Version 1.2.6</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/Forms">https://gap-packages.github.io/Forms</a></span>.
    </p>
    

bibtex: |
    @misc{ Forms1.2.6,
      author =           {Bamberg, J. and De Beule, J.},
      title =            {{Forms}, Sesquilinear and Quadratic, {V}ersion 1.2.6},
      month =            {Jul},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href                                     {https://gap-packages.github.io/Forms}
                          {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{Forms}}},
      keywords =         {Forms; Sesquilinear; Quadratic},
      printedkey =       {BB21}
    }

